# Generated by Django 4.2.1 on 2023-06-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_comment_delete_reviewmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Review",
        ),
    ]
