# Generated by Django 4.2.1 on 2023-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_comment_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
