# Generated by Django 4.2.1 on 2023-06-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                choices=[
                    ("0", "Zero stelle"),
                    ("1", "Una stella"),
                    ("2", "Due stelle"),
                    ("3", "Tre stelle"),
                    ("4", "Quattro stelle"),
                    ("5", "Cinque stelle"),
                ],
                default="star0",
                max_length=20,
            ),
        ),
    ]
