# Generated by Django 4.2.1 on 2023-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
    ]
