# Generated by Django 4.2.1 on 2023-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_productmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
