# Generated by Django 4.2.1 on 2023-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_ordermodel_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productId", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("horse", "Horse"),
                    ("horseRider", "Horse-Rider"),
                    ("stable", "Stable"),
                ],
                default="Horse",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="numberOfLikes",
            field=models.IntegerField(default=0),
        ),
    ]
