# Generated by Django 4.2.1 on 2023-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_likedproducts_productmodel_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="category",
        ),
    ]
