# Generated by Django 4.2.1 on 2023-06-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_categorymodel_remove_productmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.categorymodel",
            ),
        ),
    ]
